/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p2proyecto_oliveriraheta;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import desplazable.Desface;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.security.cert.CRLReason;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Oliver Iraheta
 */
public final class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() throws IOException {
        initComponents();
        setTitle("CANVAS");
        setInicioSesion();
        desplace = new Desface();
        cargarArchivos();
        Image a = Toolkit.getDefaultToolkit().createImage("src/icons/ver.png").getScaledInstance(25, 25, 0);
        jl_ver.setIcon(new ImageIcon(a));
        Image b = Toolkit.getDefaultToolkit().createImage("src/icons/nover.png").getScaledInstance(25, 25, 0);
        jl_noVer.setIcon(new ImageIcon(b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Contrase = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jl_LogoUnitec = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bg_opcRecu = new javax.swing.ButtonGroup();
        jf_registro = new javax.swing.JFrame();
        jp_panelSuperior = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jl_menuIcon = new javax.swing.JLabel();
        jp_panelInferior = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jl_Alumno = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jl_Clase = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jl_Maestro = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jl_Asignar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jp_desplazable = new javax.swing.JPanel();
        jd_modificar = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_maestro = new javax.swing.JTree();
        jp_fondoMod = new javax.swing.JPanel();
        pf_confirmarContraMod = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        pf_ContraMod = new javax.swing.JPasswordField();
        jl_errorContraMaestro = new javax.swing.JLabel();
        jl_ver = new javax.swing.JLabel();
        jl_noVer = new javax.swing.JLabel();
        jp_modMaestros = new javax.swing.JPanel();
        tf_identidadMaestro = new javax.swing.JTextField();
        tf_nombreMaestro = new javax.swing.JTextField();
        tf_sueldoMaestro = new javax.swing.JTextField();
        tf_usuarioMaestro = new javax.swing.JTextField();
        tf_profesionMaestro = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_clasesMaestro = new javax.swing.JList<>();
        jb_crearMaestro = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_rolMod = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jb_confirmar = new javax.swing.JButton();
        pm_menuMod = new javax.swing.JPopupMenu();
        mi_mod = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        jp_superior = new javax.swing.JPanel();
        jl_logoPortal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jp_principal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf_usuario = new javax.swing.JTextField();
        jb_ingresar = new javax.swing.JButton();
        jl_olvidar = new javax.swing.JLabel();
        pf_contra = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jl_enlaceAsistencia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jb_CambioContra = new javax.swing.JButton();

        jd_Contrase.setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(36, 71, 106));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Asistente para recuperara contraseña o usuario");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 71, 106));
        jLabel3.setText("¿Qué necesitas hacer?");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(jl_LogoUnitec, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_LogoUnitec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jd_Contrase.getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(236, 240, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        bg_opcRecu.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("No recuerdo mi contraseña");
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 26, 211, 33));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        bg_opcRecu.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("No recuerdo mi usuario de correo");
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 71, 267, 37));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 521, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Salir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 252, 244, 28));

        jButton2.setBackground(new java.awt.Color(37, 71, 106));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Continuar");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 252, 244, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Tutorial para uso del asistente");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 314, 225, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jd_Contrase.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jf_registro.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jf_registroComponentResized(evt);
            }
        });
        jf_registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_panelSuperior.setBackground(new java.awt.Color(37, 71, 106));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jl_nombre.setBackground(new java.awt.Color(236, 240, 245));
        jl_nombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_nombre.setForeground(new java.awt.Color(37, 71, 106));
        jl_nombre.setText("¡Hola Oliver Iraheta Estrada!");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jl_menuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_menuIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_panelSuperiorLayout = new javax.swing.GroupLayout(jp_panelSuperior);
        jp_panelSuperior.setLayout(jp_panelSuperiorLayout);
        jp_panelSuperiorLayout.setHorizontalGroup(
            jp_panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jp_panelSuperiorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jl_menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_panelSuperiorLayout.setVerticalGroup(
            jp_panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jf_registro.getContentPane().add(jp_panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1020, 210));

        jp_panelInferior.setBackground(new java.awt.Color(236, 240, 245));
        jp_panelInferior.setPreferredSize(new java.awt.Dimension(650, 430));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 71, 106));
        jLabel11.setText("Este es tu nuevo Portal de UNITEC.");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Aquí encontrarás todas tus aplicaciones y herramientas de trabajo de siempre y también algunas nuevas que te serán muy útiles.   ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Alumno");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jl_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jl_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Clases");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jl_Clase, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jl_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Maestro");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jl_Maestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl_Maestro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Asignar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jl_Asignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jl_Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_panelInferiorLayout = new javax.swing.GroupLayout(jp_panelInferior);
        jp_panelInferior.setLayout(jp_panelInferiorLayout);
        jp_panelInferiorLayout.setHorizontalGroup(
            jp_panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_panelInferiorLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jp_panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_panelInferiorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jp_panelInferiorLayout.setVerticalGroup(
            jp_panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelInferiorLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(538, 538, 538))
        );

        jf_registro.getContentPane().add(jp_panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 1020, 850));

        jp_desplazable.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jp_desplazableLayout = new javax.swing.GroupLayout(jp_desplazable);
        jp_desplazable.setLayout(jp_desplazableLayout);
        jp_desplazableLayout.setHorizontalGroup(
            jp_desplazableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jp_desplazableLayout.setVerticalGroup(
            jp_desplazableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jf_registro.getContentPane().add(jp_desplazable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 870));

        jd_modificar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_modificarWindowClosed(evt);
            }
        });
        jd_modificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(236, 240, 245));

        jPanel15.setBackground(new java.awt.Color(37, 71, 106));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DATOS");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(null);

        jt_maestro.setBackground(new java.awt.Color(236, 240, 245));
        jt_maestro.setBorder(null);
        jt_maestro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jt_maestro.setForeground(new java.awt.Color(37, 71, 106));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("UNITEC");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Maestros");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Alumnos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Registro");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Clases");
        treeNode1.add(treeNode2);
        jt_maestro.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_maestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_maestroMouseClicked(evt);
            }
        });
        jt_maestro.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jt_maestroValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jt_maestro);

        jp_fondoMod.setBackground(new java.awt.Color(236, 240, 245));

        pf_confirmarContraMod.setBackground(new java.awt.Color(236, 240, 245));
        pf_confirmarContraMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pf_confirmarContraMod.setBorder(null);
        pf_confirmarContraMod.setEchoChar('*');

        pf_ContraMod.setBackground(new java.awt.Color(236, 240, 245));
        pf_ContraMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pf_ContraMod.setBorder(null);
        pf_ContraMod.setEchoChar('*');

        jl_errorContraMaestro.setForeground(new java.awt.Color(255, 0, 51));
        jl_errorContraMaestro.setText("Las contraseñas no coinciden");

        jl_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_verMouseClicked(evt);
            }
        });

        jl_noVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_noVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_noVerMouseClicked(evt);
            }
        });

        jp_modMaestros.setBackground(new java.awt.Color(236, 240, 245));
        jp_modMaestros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_identidadMaestro.setBackground(new java.awt.Color(236, 240, 245));
        tf_identidadMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_identidadMaestro.setBorder(null);
        jp_modMaestros.add(tf_identidadMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 245, 20));

        tf_nombreMaestro.setBackground(new java.awt.Color(236, 240, 245));
        tf_nombreMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nombreMaestro.setBorder(null);
        jp_modMaestros.add(tf_nombreMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 245, 20));

        tf_sueldoMaestro.setBackground(new java.awt.Color(236, 240, 245));
        tf_sueldoMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_sueldoMaestro.setBorder(null);
        jp_modMaestros.add(tf_sueldoMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 245, 20));

        tf_usuarioMaestro.setBackground(new java.awt.Color(236, 240, 245));
        tf_usuarioMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_usuarioMaestro.setBorder(null);
        jp_modMaestros.add(tf_usuarioMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 245, 20));

        tf_profesionMaestro.setBackground(new java.awt.Color(236, 240, 245));
        tf_profesionMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_profesionMaestro.setBorder(null);
        jp_modMaestros.add(tf_profesionMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 245, 20));
        jp_modMaestros.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 245, 10));
        jp_modMaestros.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 245, 10));
        jp_modMaestros.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 245, 10));
        jp_modMaestros.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 245, 10));
        jp_modMaestros.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 245, 10));

        jl_clasesMaestro.setBackground(new java.awt.Color(236, 240, 245));
        jl_clasesMaestro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_clasesMaestro.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(jl_clasesMaestro);

        jp_modMaestros.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 158, 194));

        jb_crearMaestro.setBackground(new java.awt.Color(236, 240, 245));
        jb_crearMaestro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jb_crearMaestro.setForeground(new java.awt.Color(37, 71, 106));
        jb_crearMaestro.setText("CREAR MAESTRO");
        jb_crearMaestro.setBorder(null);
        jb_crearMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMaestroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_crearMaestroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_crearMaestroMouseExited(evt);
            }
        });
        jp_modMaestros.add(jb_crearMaestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 146, 39));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(37, 71, 106));
        jLabel17.setText("Usuario");
        jp_modMaestros.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(37, 71, 106));
        jLabel18.setText("Clases");
        jp_modMaestros.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(37, 71, 106));
        jLabel19.setText("Sueldo");
        jp_modMaestros.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(37, 71, 106));
        jLabel20.setText("Nombre");
        jp_modMaestros.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(37, 71, 106));
        jLabel21.setText("Profesion");
        jp_modMaestros.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(37, 71, 106));
        jLabel25.setText("No. Identidad");
        jp_modMaestros.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(37, 71, 106));
        jLabel22.setText("Confirmar Contraseña");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(37, 71, 106));
        jLabel24.setText("Contraseña");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(37, 71, 106));
        jLabel26.setText("Rol");

        tf_rolMod.setBackground(new java.awt.Color(236, 240, 245));
        tf_rolMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_rolMod.setBorder(null);

        jb_confirmar.setBackground(new java.awt.Color(236, 240, 245));
        jb_confirmar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jb_confirmar.setForeground(new java.awt.Color(37, 71, 106));
        jb_confirmar.setText("GUARDAR CAMBIOS");
        jb_confirmar.setBorder(null);
        jb_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_confirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_confirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jb_confirmarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_fondoModLayout = new javax.swing.GroupLayout(jp_fondoMod);
        jp_fondoMod.setLayout(jp_fondoModLayout);
        jp_fondoModLayout.setHorizontalGroup(
            jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fondoModLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_fondoModLayout.createSequentialGroup()
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_ContraMod, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_noVer, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jl_ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_confirmar)
                        .addGap(182, 182, 182))
                    .addGroup(jp_fondoModLayout.createSequentialGroup()
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_errorContraMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_fondoModLayout.createSequentialGroup()
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_confirmarContraMod, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_rolMod, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_fondoModLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jp_modMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jp_fondoModLayout.setVerticalGroup(
            jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoModLayout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoModLayout.createSequentialGroup()
                        .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_noVer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jp_fondoModLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pf_ContraMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_fondoModLayout.createSequentialGroup()
                                .addComponent(jb_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pf_confirmarContraMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fondoModLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_rolMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_errorContraMaestro)
                .addGap(80, 80, 80))
            .addGroup(jp_fondoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_fondoModLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jp_modMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_fondoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_fondoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );

        jd_modificar.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 670));

        mi_mod.setText("Modificar");
        mi_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modActionPerformed(evt);
            }
        });
        pm_menuMod.add(mi_mod);

        mi_eliminar.setText("Eliminar");
        mi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarActionPerformed(evt);
            }
        });
        pm_menuMod.add(mi_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_superior.setBackground(new java.awt.Color(37, 71, 106));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 71, 106));
        jLabel1.setText("Inicio de sesión");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 71, 106));
        jLabel2.setText("Accede a tu cuenta");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_superiorLayout = new javax.swing.GroupLayout(jp_superior);
        jp_superior.setLayout(jp_superiorLayout);
        jp_superiorLayout.setHorizontalGroup(
            jp_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_superiorLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(jp_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_superiorLayout.createSequentialGroup()
                        .addComponent(jl_logoPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jp_superiorLayout.setVerticalGroup(
            jp_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_logoPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jp_superior, java.awt.BorderLayout.PAGE_START);

        jp_principal.setBackground(new java.awt.Color(236, 240, 245));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tf_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_usuario.setForeground(new java.awt.Color(153, 153, 153));
        tf_usuario.setText("Ingrese su usuario de correo, sin incluir el \"@unitec.edu\"");
        tf_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_usuarioMouseClicked(evt);
            }
        });

        jb_ingresar.setBackground(new java.awt.Color(37, 71, 106));
        jb_ingresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        jb_ingresar.setText("Ingresar");
        jb_ingresar.setBorder(null);
        jb_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });

        jl_olvidar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_olvidar.setForeground(new java.awt.Color(36, 71, 106));
        jl_olvidar.setText("¿Olvidaste tu contraseña?");
        jl_olvidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_olvidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_olvidarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_olvidarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_olvidarMouseExited(evt);
            }
        });

        pf_contra.setForeground(new java.awt.Color(153, 153, 153));
        pf_contra.setText("Contraseña");
        pf_contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_contraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf_contra)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jb_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_olvidar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jl_olvidar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(55, 174, 225));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(4);
        jTextArea1.setText("\nLas credenciales de acceso al Portal son las mismas que usas para acceder a tu \ncuenta de correo electrónico de UNITEC.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("pasos que encontrarás en ");

        jl_enlaceAsistencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_enlaceAsistencia.setForeground(new java.awt.Color(51, 204, 255));
        jl_enlaceAsistencia.setText("este enlace.");
        jl_enlaceAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_enlaceAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_enlaceAsistenciaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Si tienes problemas con el ingreso al portal puedes restablecer tu contraseña siguiendo los  ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Si necesitas cambiar tu contraseña te recomendamos que hagas uso del asistente que");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("encontrarás aquí:");

        jb_CambioContra.setBackground(new java.awt.Color(37, 71, 106));
        jb_CambioContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_CambioContra.setForeground(new java.awt.Color(255, 255, 255));
        jb_CambioContra.setText("Asistente para cambio de contraseña");
        jb_CambioContra.setBorder(null);
        jb_CambioContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_CambioContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CambioContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_enlaceAsistencia))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jb_CambioContra, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jl_enlaceAsistencia))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_CambioContra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_principalLayout = new javax.swing.GroupLayout(jp_principal);
        jp_principal.setLayout(jp_principalLayout);
        jp_principalLayout.setHorizontalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_principalLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jp_principalLayout.setVerticalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_principalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jp_principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_enlaceAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_enlaceAsistenciaMouseClicked

        try {
            Desktop.getDesktop().browse(new URI(enlaceAsistenciaJaguar));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jl_enlaceAsistenciaMouseClicked

    private void tf_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_usuarioMouseClicked
        // TODO add your handling code here:
        if (tf_usuario.getText().equals("Ingrese su usuario de correo, sin incluir el \"@unitec.edu\"")) {
            tf_usuario.setText("");
            tf_usuario.setForeground(Color.black);
        }

        if (pf_contra.getText().equals("")) {
            pf_contra.setText("Contraseña");
            pf_contra.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tf_usuarioMouseClicked

    private void pf_contraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_contraMouseClicked
        // TODO add your handling code here:
        if (pf_contra.getText().equals("Contraseña")) {
            pf_contra.setText("");
            pf_contra.setForeground(Color.black);
        }

        if (tf_usuario.getText().equals("")) {
            tf_usuario.setText("Ingrese su usuario de correo, sin incluir el \"@unitec.edu\"");
            tf_usuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_pf_contraMouseClicked

    private void jl_olvidarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_olvidarMouseEntered
        // TODO add your handling code here:
        Font font = new Font("Segoe UI", 3, 14);
        jl_olvidar.setFont(font);
    }//GEN-LAST:event_jl_olvidarMouseEntered

    private void jl_olvidarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_olvidarMouseExited
        // TODO add your handling code here
        Font font = new Font("Segoe UI", 0, 14);
        jl_olvidar.setFont(font);
    }//GEN-LAST:event_jl_olvidarMouseExited

    private void jl_olvidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_olvidarMouseClicked
        // TODO add your handling code here:
        setJDContrasenia();
    }//GEN-LAST:event_jl_olvidarMouseClicked

    private void jb_CambioContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CambioContraActionPerformed
        // TODO add your handling code here:
        setJDContrasenia();
    }//GEN-LAST:event_jb_CambioContraActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_Contrase.setVisible(false);
        setInicioSesion();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jf_registroComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jf_registroComponentResized
        // TODO add your handling code here:
        jp_desplazable.setSize(jp_desplazable.getWidth(), jf_registro.getHeight());
        resizedJFmenu();
    }//GEN-LAST:event_jf_registroComponentResized

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:
        int existe = 0;

        for (Alumno listaAlumno : alumnos) {
            if (listaAlumno.getUsuario().equals(tf_usuario.getText()) && listaAlumno.getPassword().equals(pf_contra.getText())) {
                existe = 3;
            }
        }
        for (Maestro maestro : maestros) {
            if (maestro.getUsuario().equals(tf_usuario.getText()) && maestro.getPassword().equals(pf_contra.getText())) {
                existe = 2;
            }
        }
        for (Registro listaRegistro : registros) {
            if (listaRegistro.getUsuario().equals(tf_usuario.getText()) && listaRegistro.getPassword().equals(pf_contra.getText())) {
                existe = 1;
            }
        }

        if (existe == 0) {
            JOptionPane.showMessageDialog(this, "Usuario NO Encontrado");
        }
        if (existe == 1) {
            this.setVisible(false);
            usuario = tf_usuario.getText();
            setJFmenu();
        }
        if (existe == 2) {
            this.setVisible(false);
            usuario = tf_usuario.getText();

        }
        if (existe == 3) {
            this.setVisible(false);
            usuario = tf_usuario.getText();

        }


    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jl_menuIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_menuIconMouseClicked
        // TODO add your handling code here:
//Harcelo con hilos
        if (jp_desplazable.getX() == 0) {
            desplace.desplazarIzquierda(jp_desplazable, jp_desplazable.getX(), -200, 10, 10);
//            desplace.desplazarIzquierda(jp_panelSuperior, jp_panelSuperior.getX(), -200, 10, 10);
//            desplace.desplazarIzquierda(jp_panelInferior, jp_panelInferior.getX(), -200, 10, 10);
            jp_panelSuperior.setBounds(jp_panelSuperior.getX() - 200, jp_panelSuperior.getY(), jp_panelSuperior.getWidth() + 200, jp_panelSuperior.getHeight());
            jp_panelInferior.setBounds(jp_panelInferior.getX() - 200, jp_panelInferior.getY(), jp_panelInferior.getWidth() + 200, jp_panelInferior.getHeight());
        } else {
            desplace.desplazarDerecha(jp_desplazable, jp_desplazable.getX(), 0, 10, 20);
//            desplace.desplazarDerecha(jp_panelSuperior, jp_panelSuperior.getX(), 0, 10, 10);
//            desplace.desplazarDerecha(jp_panelInferior, jp_panelInferior.getX(), 0, 10, 10);
            jp_panelSuperior.setBounds(jp_panelSuperior.getX() + 200, jp_panelSuperior.getY(), jp_panelSuperior.getWidth() - 200, jp_panelSuperior.getHeight());
            jp_panelInferior.setBounds(jp_panelInferior.getX() + 200, jp_panelInferior.getY(), jp_panelInferior.getWidth() - 200, jp_panelInferior.getHeight());
        }
    }//GEN-LAST:event_jl_menuIconMouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        // TODO add your handling code here:
        jPanel12.setBackground(Color.red);
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        // TODO add your handling code here:
        jPanel12.setBackground(Color.white);
    }//GEN-LAST:event_jPanel12MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
        jPanel10.setBackground(Color.red);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(Color.white);
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        // TODO add your handling code here:
        jPanel11.setBackground(Color.red);
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        // TODO add your handling code here:
        jPanel11.setBackground(Color.white);
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane, "a");
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
        jPanel13.setBackground(Color.red);
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
        jPanel13.setBackground(Color.white);
    }//GEN-LAST:event_jPanel13MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI(enlaceAsistenciaJaguar));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        setTreeMaestro();
        jd_modificar.pack();
        jd_modificar.setLocationRelativeTo(jf_registro);
        jd_modificar.setModal(true);
        jp_fondoMod.setVisible(true);
        jp_modMaestros.setVisible(true);
        jl_ver.setVisible(false);
        jl_noVer.setVisible(true);
        jl_errorContraMaestro.setVisible(false);
        jb_confirmar.setVisible(false);
        jd_modificar.setVisible(true);
        jd_modificar.setResizable(false);

    }//GEN-LAST:event_jPanel12MouseClicked

    private void jb_confirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_confirmarMouseEntered
        // TODO add your handling code here:
        jb_confirmar.setBackground(new Color(37, 71, 106));
        jb_confirmar.setForeground(Color.white);
    }//GEN-LAST:event_jb_confirmarMouseEntered

    private void jb_confirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_confirmarMouseExited
        // TODO add your handling code here:
        jb_confirmar.setBackground(new Color(236, 240, 245));
        jb_confirmar.setForeground(new Color(37, 71, 106));
    }//GEN-LAST:event_jb_confirmarMouseExited

    private void jb_crearMaestroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMaestroMouseEntered
        // TODO add your handling code here:
        jb_crearMaestro.setBackground(new Color(37, 71, 106));
        jb_crearMaestro.setForeground(Color.white);
    }//GEN-LAST:event_jb_crearMaestroMouseEntered

    private void jb_crearMaestroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMaestroMouseExited
        // TODO add your handling code here:
        jb_crearMaestro.setBackground(new Color(236, 240, 245));
        jb_crearMaestro.setForeground(new Color(37, 71, 106));
    }//GEN-LAST:event_jb_crearMaestroMouseExited

    private void jb_crearMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMaestroMouseClicked
        // TODO add your handling code here:
//        int id, int sueldo, String nombre, String profesion, String usuario, String password)
        if (pf_ContraMod.getText().equals(pf_confirmarContraMod.getText())) {
            Maestro newMaestro = new Maestro(Integer.parseInt(tf_sueldoMaestro.getText()), tf_nombreMaestro.getText(), tf_profesionMaestro.getText(), tf_usuarioMaestro.getText(), pf_ContraMod.getText(), tf_identidadMaestro.getText(), tf_rolMod.getText());
            boolean noExiste = true;
            for (Maestro m : maestros) {
                if (m.getId().equals(newMaestro.getId()) || m.getNombre().equals(newMaestro.getNombre()) || m.getUsuario().equals(newMaestro.getUsuario())) {
                    noExiste = false;
                }
            }
            if (noExiste) {
                maestros.add(newMaestro);
                escribirArchivo();
                jl_errorContraMaestro.setVisible(false);
                setTreeMaestro();
                JOptionPane.showMessageDialog(jd_modificar, "MAESTRO CREADO");
                jl_errorContraMaestro.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(jd_modificar, "MAESTRO YA EXISTE");
            }
        } else {
            jl_errorContraMaestro.setVisible(true);
        }


    }//GEN-LAST:event_jb_crearMaestroMouseClicked

    private void jl_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_verMouseClicked
        // TODO add your handling code here:
        jl_noVer.setVisible(true);
        jl_ver.setVisible(false);
        pf_ContraMod.setEchoChar((char) 0);
        pf_confirmarContraMod.setEchoChar((char) 0);

    }//GEN-LAST:event_jl_verMouseClicked

    private void jl_noVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_noVerMouseClicked
        // TODO add your handling code here:
        jl_noVer.setVisible(false);
        jl_ver.setVisible(true);
        pf_ContraMod.setEchoChar('*');
        pf_confirmarContraMod.setEchoChar('*');
    }//GEN-LAST:event_jl_noVerMouseClicked

    private void jt_maestroValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jt_maestroValueChanged


    }//GEN-LAST:event_jt_maestroValueChanged

    private void jd_modificarWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_modificarWindowClosed
        // TODO add your handling code here:
        jp_modMaestros.setVisible(false);
        jp_fondoMod.setVisible(false);
    }//GEN-LAST:event_jd_modificarWindowClosed

    private void jb_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_confirmarMouseClicked
        if (nodo_seleccionado != null) {
            if (pf_ContraMod.getText().equals(pf_confirmarContraMod.getText())) {
                DefaultTreeModel m = (DefaultTreeModel) jt_maestro.getModel();
                if (nodo_seleccionado.getUserObject() instanceof Maestro) {
                    maestro_seleccionado.setId(tf_identidadMaestro.getText());
                    maestro_seleccionado.setNombre(tf_nombreMaestro.getText());
                    maestro_seleccionado.setPassword(pf_ContraMod.getText());
                    maestro_seleccionado.setProfesion(tf_profesionMaestro.getText());
                    maestro_seleccionado.setSueldo(Integer.parseInt(tf_sueldoMaestro.getText()));
                    maestro_seleccionado.setUsuario(tf_usuarioMaestro.getText());
                    maestro_seleccionado.setRol(tf_rolMod.getText());
                    escribirArchivo();
                }
                JOptionPane.showMessageDialog(jd_modificar, "Cambios Guardados");
            } else {
                jl_errorContraMaestro.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(jd_modificar, "Seleccione un usuario");
        }


    }//GEN-LAST:event_jb_confirmarMouseClicked

    private void jt_maestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_maestroMouseClicked

        if (evt.isMetaDown()) {
            int row = jt_maestro.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_maestro.setSelectionRow(row);
            Object v1 = jt_maestro.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            pm_menuMod.show(evt.getComponent(), evt.getX(), evt.getY());
        } else {
            if (nodo_seleccionado.getUserObject() instanceof Maestro) {
                jt_maestro.clearSelection();
                jb_crearMaestro.setVisible(true);
                jb_confirmar.setVisible(false);
                clearMaestroMod();
            }
        }


    }//GEN-LAST:event_jt_maestroMouseClicked

    private void mi_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modActionPerformed
        jb_crearMaestro.setVisible(false);
        if (nodo_seleccionado.getUserObject() instanceof Maestro) {
            maestro_seleccionado = (Maestro) nodo_seleccionado.getUserObject();
            pf_ContraMod.setEchoChar((char) 0);
            pf_confirmarContraMod.setEchoChar((char) 0);
            jp_modMaestros.setVisible(true);
            tf_identidadMaestro.setText(maestro_seleccionado.getId());
            tf_nombreMaestro.setText(maestro_seleccionado.getNombre());
            tf_profesionMaestro.setText(maestro_seleccionado.getProfesion());
            tf_sueldoMaestro.setText(maestro_seleccionado.getSueldo() + "");
            tf_usuarioMaestro.setText(maestro_seleccionado.getUsuario());
            pf_ContraMod.setText(maestro_seleccionado.getPassword());
            pf_confirmarContraMod.setText("");
            tf_rolMod.setText(maestro_seleccionado.getRol());
            DefaultListModel modelo = (DefaultListModel) jl_clasesMaestro.getModel();
            modelo.clear();
            for (Clase c : maestro_seleccionado.getListaClases()) {
                modelo.addElement(c);
            }
            jl_clasesMaestro.setModel(modelo);
            jb_confirmar.setVisible(true);
        }

    }//GEN-LAST:event_mi_modActionPerformed

    private void mi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarActionPerformed

        if (nodo_seleccionado.getUserObject() instanceof Maestro) {
            maestros.remove(nodo_seleccionado.getUserObject());
            clearMaestroMod();
        }
        setTreeMaestro();
        escribirArchivo();

    }//GEN-LAST:event_mi_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InicioSesion().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_opcRecu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_CambioContra;
    private javax.swing.JButton jb_confirmar;
    private javax.swing.JButton jb_crearMaestro;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JDialog jd_Contrase;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JFrame jf_registro;
    private javax.swing.JLabel jl_Alumno;
    private javax.swing.JLabel jl_Asignar;
    private javax.swing.JLabel jl_Clase;
    private javax.swing.JLabel jl_LogoUnitec;
    private javax.swing.JLabel jl_Maestro;
    private javax.swing.JList<String> jl_clasesMaestro;
    private javax.swing.JLabel jl_enlaceAsistencia;
    private javax.swing.JLabel jl_errorContraMaestro;
    private javax.swing.JLabel jl_logoPortal;
    private javax.swing.JLabel jl_menuIcon;
    private javax.swing.JLabel jl_noVer;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_olvidar;
    private javax.swing.JLabel jl_ver;
    private javax.swing.JPanel jp_desplazable;
    private javax.swing.JPanel jp_fondoMod;
    private javax.swing.JPanel jp_modMaestros;
    private javax.swing.JPanel jp_panelInferior;
    private javax.swing.JPanel jp_panelSuperior;
    private javax.swing.JPanel jp_principal;
    private javax.swing.JPanel jp_superior;
    private javax.swing.JTree jt_maestro;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JMenuItem mi_mod;
    private javax.swing.JPasswordField pf_ContraMod;
    private javax.swing.JPasswordField pf_confirmarContraMod;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPopupMenu pm_menuMod;
    private javax.swing.JTextField tf_identidadMaestro;
    private javax.swing.JTextField tf_nombreMaestro;
    private javax.swing.JTextField tf_profesionMaestro;
    private javax.swing.JTextField tf_rolMod;
    private javax.swing.JTextField tf_sueldoMaestro;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioMaestro;
    // End of variables declaration//GEN-END:variables
 /*
    cosas a agregar:
    - /InicioSesion/ cuando de enter que inicie sesion

     */

//mis variables
    private DefaultMutableTreeNode nodo_seleccionado;
    private Maestro maestro_seleccionado;
    private Registro registro_seleccionado;
    private Alumno alumno_seleccionado;
    private Clase clase_seleccionada;

    Desface desplace;
    private final String enlaceAsistenciaJaguar = "https://unitec.edu/asistenciajaguar/";
    private ArrayList<Maestro> maestros;
    private ArrayList<Registro> registros;
    private ArrayList<Alumno> alumnos;
    private ArrayList<Clase> clases;

    public String usuario = "";

//mis metodos para setear 
    public void cargarArchivos() {
        AdmMaestro am = new AdmMaestro("./Maestros.oli");
        am.cargarArchivo();
        maestros = am.getListaMaestros();
        AdmRegistro ar = new AdmRegistro("./Registro.oli");
        ar.cargarArchivo();
        registros = ar.getListaRegistros();
        AdmAlumno aa = new AdmAlumno("./Alumnos.oli");
        aa.cargarArchivo();
        alumnos = aa.getListaAlumnos();
        AdmClase ac = new AdmClase("./Clase.oli");
        ac.cargarArchivo();
        clases = ac.getListaClases();

    }

    public void escribirArchivo() {
        AdmMaestro am = new AdmMaestro("./Maestros.oli");
        am.setListaMaestros(maestros);
        am.escribirArchivo();
        AdmRegistro ar = new AdmRegistro("./Registro.oli");
        ar.setListaRegistros(registros);
        ar.escribirArchivo();
        AdmAlumno aa = new AdmAlumno("./Alumnos.oli");
        aa.setListaPersonas(alumnos);
        aa.escribirArchivo();
        AdmClase ac = new AdmClase("./Clase.oli");
        ac.setListaClases(clases);
        ac.escribirArchivo();
    }

    public void setTreeMaestro() {
        DefaultTreeModel modelo = (DefaultTreeModel) jt_maestro.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        ((DefaultMutableTreeNode) raiz.getChildAt(0)).removeAllChildren();
        for (Maestro m : maestros) {
            ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(new DefaultMutableTreeNode(m));
        }
        for (Alumno a : alumnos) {
            ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(new DefaultMutableTreeNode(a));
        }
        for (Registro a : registros) {
            ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(new DefaultMutableTreeNode(a));
        }
        for (Clase a : clases) {
            ((DefaultMutableTreeNode) raiz.getChildAt(3)).add(new DefaultMutableTreeNode(a));
        }
        modelo.reload();
        jt_maestro.setModel(modelo);
    }

    public void resizedJFmenu() {
        jp_panelInferior.setSize(jf_registro.getWidth() - jp_desplazable.getWidth(), (jf_registro.getHeight() - jp_panelSuperior.getHeight()));
        jp_panelSuperior.setSize(jf_registro.getWidth() - jp_desplazable.getWidth(), (jf_registro.getHeight() - jp_panelInferior.getHeight()));
        jPanel9.setBounds(100, jPanel9.getY(), jp_panelSuperior.getWidth() - 200, jPanel9.getHeight());
        jPanel7.setBounds(jPanel9.getX(), jPanel7.getY(), jPanel9.getWidth(), jPanel7.getHeight());
    }

    public void setJFmenu() {
        jf_registro.pack();
        jf_registro.setLocationRelativeTo(this);
        jf_registro.setExtendedState(6);
        jl_nombre.setText("¡Hola " + usuario + " !");

        Image a = Toolkit.getDefaultToolkit().createImage("src/icons/student.jpg").getScaledInstance(120, 120, 0);
        jl_Alumno.setIcon(new ImageIcon(a));
        Image b = Toolkit.getDefaultToolkit().createImage("src/icons/asignar.png").getScaledInstance(120, 120, 0);
        jl_Asignar.setIcon(new ImageIcon(b));
        Image c = Toolkit.getDefaultToolkit().createImage("src/icons/teacher.jpg").getScaledInstance(120, 120, 0);
        jl_Maestro.setIcon(new ImageIcon(c));
        Image d = Toolkit.getDefaultToolkit().createImage("src/icons/menu.png").getScaledInstance(35, 35, 0);
        jl_menuIcon.setIcon(new ImageIcon(d));
        Image e = Toolkit.getDefaultToolkit().createImage("src/icons/clases.jpg").getScaledInstance(120, 120, 0);
        jl_Clase.setIcon(new ImageIcon(e));

        jf_registro.setVisible(true);
    }

    public void setJDContrasenia() {

        jd_Contrase.pack();
        jd_Contrase.setLocationRelativeTo(this);
        jd_Contrase.setModal(true);
        Image e = Toolkit.getDefaultToolkit().createImage("src/icons/logoUnitec.png").getScaledInstance(198, 53, 0);
        jl_logoPortal.setIcon(new ImageIcon(e));
        jd_Contrase.setVisible(true);
    }

    public void setInicioSesion() {

        this.pack();
        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        Image e = Toolkit.getDefaultToolkit().createImage("src/icons/logoPortal.png.png").getScaledInstance(208, 43, 0);
        jl_logoPortal.setIcon(new ImageIcon(e));

        this.setVisible(true);
    }

    public void clearMaestroMod() {
        tf_identidadMaestro.setText("");
        tf_nombreMaestro.setText("");
        tf_profesionMaestro.setText("");
        tf_sueldoMaestro.setText("");
        tf_usuarioMaestro.setText("");
        pf_ContraMod.setText("");
        pf_confirmarContraMod.setText("");
        tf_rolMod.setText("");
    }

}
